// This file is auto-generated by ./bin/rails stimulus:manifest:update
// To add new controllers, run: rails generate stimulus <name>

import { application } from "./application"

import LiveCounterController from "./live_counter_controller"
import EventFeedController from "./event_feed_controller"
import StatsController from "./stats_controller"
import SystemHealthController from "./system_health_controller"

application.register("live-counter", LiveCounterController)
application.register("event-feed", EventFeedController)
application.register("stats", StatsController)
application.register("system-health", SystemHealthController)
